### ISSUE TITLE
Allowing LARS as a Resnet Optimizer

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#177] opened 2019-01-17 19:25 UTC
There was consensus among submitters in v0.5.0 that we want to enable LARS for resnet to enable scaling the benchmark on larger systems.

**Comment by bitfort** [comment] 2019-02-28 19:55
SWG:

Generally agree that LARS should be allowed for resent assuming it converges. 

AI(Google) to show it converges. Specifically -- show there exists a resnet with LARS which hits accuracy 75.9 and provide parameters for people.

**Comment by bitfort** [comment] 2019-03-07 19:37
SWG Notes:

Google shared code for this. 

There seems to be support for limiting LARS to large scales, such as 16k+ (exact number TBD).

AI(Google) -- File a PR, with a high level summary.

**Comment by bitfort** [comment] 2019-03-14 18:11
SWG Notes:

We agree to allow LARS for 16k and higher for resnet (pending PR by google and review).

**Comment by petermattson** [comment] 2019-05-30 22:32
No batch size limit, see SWG: in 196.

**Comment by petermattson** [comment] 2020-05-29 20:34
Made active again, since this debate is ongoing.

**Comment by petermattson** [comment] 2020-06-11 00:03
Duplicate of #346 (will be handled by the HP table merge)

**Closed as completed by petermattson** 2020-06-11 00:03 UTC
