### ISSUE TITLE
Number of runs for Each Benchmark

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#199] opened 2019-05-02 18:07 UTC
How many times should each benchmark be run?

**Comment by bitfort** [comment] 2019-05-02 18:19
SWG Notes:

Resnet - 5 (both SGD and LARS)
SSD - 5
Maskrcnn - 5
Transformer - 10
GNMT - 10
Minigo - 10

**Comment by cliffwoolley** [comment] 2019-05-18 08:05
Note that the Reinforcement learning (Minigo) number should be updated on https://github.com/mlperf/policies/blob/master/training_rules.adoc#11-benchmark-results , where it still says 20.

**Comment by petermattson** [comment] 2020-05-29 22:06
Effectively a duplicate of #155.

**Comment by petermattson** [comment] 2020-05-29 22:07
On second thought, reopen and make active to serve as reminder to get DLRM and BERT number of runs into rules.

**Comment by petermattson** [comment] 2020-06-11 00:07
Duplicate of #297

**Closed as completed by petermattson** 2020-06-11 00:07 UTC
