### ISSUE TITLE
Standardize hyper parameter specification format

### ISSUE THREAD

**Issue by jonathan-cohen-nvidia** [mlcommons/training_policies#248] opened 2019-07-23 23:53 UTC
Different implementations specify the same HP in different ways (e.g. total batch vs batch per GPU) which makes comparing and reviewing across implementations unnecessarily complex.  We should define a spec with a name/value pair for each HP with a defined semantics.  These HPs should then be specified either in a json (or similar) file with a fixed schema or via a fixed set of command line arguments & formatting.

**Comment by bitfort** [comment] 2019-08-01 18:55
SWG Notes:

This related to work being done by the Best Practices working group. Currently this is leaning towards the JSON file approach. We will let best practices WG come up with a proposal and bring it back to submitters.

**Comment by bitfort** [comment] 2020-02-06 17:59
Proposal:

This could look like a JSON file which specifies keys and the meaning for keys. This JSON file is turned into command line arguments by some infrastructure.

**Comment by petermattson** [comment] 2020-06-11 00:34
Duplicate of #346 (will be handled by the HP table merge)

**Comment by petermattson** [comment] 2020-06-11 00:34
Also handled in part by new logger.

**Closed as completed by petermattson** 2020-06-11 00:34 UTC
