### ISSUE TITLE
Resnet 50 HPs

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#196] opened 2019-04-18 18:26 UTC
LARS, polynomial learning rate, etc. -- are these additions allowed for any batch size? Optional? Package deal, pick and choose?

**Comment by bitfort** [comment] 2019-04-18 18:37
SWG Notes:

A possible pragmatic starting point: above a certain batch size, you may use new functionality (LARS, label smoothing and polynomial learning rate), below that batch size you may not use any of the new functionality. New functionality would be all-or-none for submitters: if you take piece of the new functionality you must use all the new pieces. 

Proposal is >=16k batch size allows for LARs. 

AI(Submitters):  discuss this threshold internally

**Comment by bitfort** [comment] 2019-04-25 18:16
SWG Notes:

There is support for making "LARS+Label Smoothing+Poly" a single HP "bit", i.e. you do it all or not. This simplifies the search space. 
There is an amendment proposed to remove the batch size limitation.

We will discuss again next week to see if there are concerns of LARS at smaller batch sizes (such as variance).

**Comment by bitfort** [comment] 2019-05-23 18:18
SWG Notes:

For v0.6, "LARS+Label Smoothing+Poly" is a single "package deal". There is no batch size limits on LARS.

**Comment by petermattson** [comment] 2020-05-29 22:03
Making active to ensure this is handled by revised hp policy.

**Comment by petermattson** [comment] 2020-06-11 00:05
Duplicate of #346 (will be handled by the HP table merge)

**Closed as completed by petermattson** 2020-06-11 00:05 UTC
