### ISSUE TITLE
Custom Kernel Usage

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#205] opened 2019-05-09 18:14 UTC
Some submissions in v0.5 used a custom CUDA kernel. There is interest in discussing if this is representable of user experience.

**Comment by bitfort** [comment] 2019-05-09 18:51
We believe this is a long term issue which we should explore in special topics. 

As far as handling for v0.6, it is very close to the deadline to make changes -- but we also understand that the rules are not as clear here was we would like. We will sync over email in the next few days to see if there are concrete concerns for v0.6.

**Comment by petermattson** [comment] 2020-06-11 00:08
Expect we'll need to Backlog this, but want to do it in meeting

**Comment by petermattson** [comment] 2020-06-11 00:36
closed as duplicate of #259

**Closed as completed by petermattson** 2020-06-11 00:36 UTC
