### ISSUE TITLE
Hyperparameter Plan for v0.7

### ISSUE THREAD

**Issue by bitfort** [mlcommons/training_policies#282] opened 2020-02-13 16:42 UTC
This issue captures many HP related issues, including:

- There is a request to publish HPs ahead of submission, especially for large scales.

**Comment by bitfort** [comment] 2020-02-20 16:48
A few more issues to track here
- Resnet HPs
- HP Walk through for other models
- Standardize format (json file for parameters) https://github.com/mlperf/training_policies/issues/248
- HP Borrowing and scaling rules https://github.com/mlperf/training_policies/issues/214

**Comment by bitfort** [comment] 2020-02-20 16:58
AI(Victor) - Come up with a fix to all HP issues, next week.

**Comment by bitfort** [comment] 2020-03-19 16:26
We have a list of HP proposals (and carry overs from previous rounds) we will review and for v0.7:
https://docs.google.com/spreadsheets/d/128r_G1KEE0C1PzuTnBGybeNsT-mXeORZhmWnqDgu8Ok/edit#gid=1020474538&fvid=442857665

We are asking reference leaders (owners) to clean up rows for their benchmark. Specifically, the definition should be code such as a reference cli flag or a line of reference code setting the value. 

Resnet - Being done by Victor as an example
SSD - Intel
Mask - Alibaba
GNMT - NVIDIA
Transformer - CISCO
BERT - *A Great Opportunity for YOU!*
DLRM - FB
Minigo - Google

**Comment by petermattson** [comment] 2020-06-11 00:44
Duplicate of #346 (will be handled by the HP table merge)

**Closed as completed by petermattson** 2020-06-11 00:44 UTC
